# Whenever a tag push matching pattern "v*" then run the job
on: 
  push:
    tags:
      - "v*"

jobs:
  # job id, can be anything
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Add permission for release creation. Can be made narrower according to your needs
    permissions: write-all
    # Job name, can be anything
    name: Export Game
    steps:
      # Always include the checkout step so that 
      # your project is available for Godot to export
    - name: checkout
      uses: actions/checkout@v3.3.0
    
    - name: install wine
      id: wine_install
      run: |
        sudo apt update
        sudo apt install wine64
        echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT

    - name: export game
      id: export
      # Use latest version (see releases for all versions)
      uses: darthLeviN/godot-export@v0.0.2
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://github.com/ProjectLam/godot-build-scripts/releases/download/0.0-7c6df74978-20230412/godot-linux-0.0.tar.gz
        godot_export_templates_linux_download_url: https://github.com/ProjectLam/godot-build-scripts/releases/download/0.0-7c6df74978-20230412/godot-linux-0.0.tar.gz
        godot_export_templates_windows_download_url: https://github.com/ProjectLam/godot-build-scripts/releases/download/0.0-7c6df74978-20230412/godot-windows-0.0.tar.gz
        godot_export_templates_web_download_url: https://github.com/ProjectLam/godot-build-scripts/releases/download/0.0-7c6df74978-20230412/godot-web-0.0.tar.gz
        # godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0.1/Godot_v4.0.1-stable_export_templates.tpz
        wine_path: ${{ steps.wine_install.outputs.WINE_PATH }} # set the wine path here which is the output of the wine_install step
        relative_project_path: ./
        archive_output: true

      # This release action has worked well for me. However, you can most likely use any release action of your choosing.
      # https://github.com/ncipollo/release-action
    - name: create release
      uses: ncipollo/release-action@v1.12.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: ${{ github.ref_name }}
        artifacts: ${{ steps.export.outputs.archive_directory }}/*
